# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/biin/smsgate-dev

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/biin/smsgate-dev

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/biin/smsgate-dev/CMakeFiles /home/biin/smsgate-dev/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/biin/smsgate-dev/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ghelper

# Build rule for target.
ghelper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ghelper
.PHONY : ghelper

# fast build rule for target.
ghelper/fast:
	$(MAKE) -f CMakeFiles/ghelper.dir/build.make CMakeFiles/ghelper.dir/build
.PHONY : ghelper/fast

#=============================================================================
# Target rules for targets named smsgate

# Build rule for target.
smsgate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smsgate
.PHONY : smsgate

# fast build rule for target.
smsgate/fast:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/build
.PHONY : smsgate/fast

#=============================================================================
# Target rules for targets named thelper

# Build rule for target.
thelper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thelper
.PHONY : thelper

# fast build rule for target.
thelper/fast:
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/build
.PHONY : thelper/fast

core/ConfigManager.o: core/ConfigManager.cpp.o
.PHONY : core/ConfigManager.o

# target to build an object file
core/ConfigManager.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/ConfigManager.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/ConfigManager.cpp.o
.PHONY : core/ConfigManager.cpp.o

core/ConfigManager.i: core/ConfigManager.cpp.i
.PHONY : core/ConfigManager.i

# target to preprocess a source file
core/ConfigManager.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/ConfigManager.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/ConfigManager.cpp.i
.PHONY : core/ConfigManager.cpp.i

core/ConfigManager.s: core/ConfigManager.cpp.s
.PHONY : core/ConfigManager.s

# target to generate assembly for a file
core/ConfigManager.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/ConfigManager.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/ConfigManager.cpp.s
.PHONY : core/ConfigManager.cpp.s

core/DLRHandler.o: core/DLRHandler.cpp.o
.PHONY : core/DLRHandler.o

# target to build an object file
core/DLRHandler.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/DLRHandler.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/DLRHandler.cpp.o
.PHONY : core/DLRHandler.cpp.o

core/DLRHandler.i: core/DLRHandler.cpp.i
.PHONY : core/DLRHandler.i

# target to preprocess a source file
core/DLRHandler.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/DLRHandler.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/DLRHandler.cpp.i
.PHONY : core/DLRHandler.cpp.i

core/DLRHandler.s: core/DLRHandler.cpp.s
.PHONY : core/DLRHandler.s

# target to generate assembly for a file
core/DLRHandler.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/DLRHandler.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/DLRHandler.cpp.s
.PHONY : core/DLRHandler.cpp.s

core/DeliveryHandler.o: core/DeliveryHandler.cpp.o
.PHONY : core/DeliveryHandler.o

# target to build an object file
core/DeliveryHandler.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/DeliveryHandler.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/DeliveryHandler.cpp.o
.PHONY : core/DeliveryHandler.cpp.o

core/DeliveryHandler.i: core/DeliveryHandler.cpp.i
.PHONY : core/DeliveryHandler.i

# target to preprocess a source file
core/DeliveryHandler.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/DeliveryHandler.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/DeliveryHandler.cpp.i
.PHONY : core/DeliveryHandler.cpp.i

core/DeliveryHandler.s: core/DeliveryHandler.cpp.s
.PHONY : core/DeliveryHandler.s

# target to generate assembly for a file
core/DeliveryHandler.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/DeliveryHandler.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/DeliveryHandler.cpp.s
.PHONY : core/DeliveryHandler.cpp.s

core/GateManager.o: core/GateManager.cpp.o
.PHONY : core/GateManager.o

# target to build an object file
core/GateManager.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/GateManager.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/GateManager.cpp.o
.PHONY : core/GateManager.cpp.o

core/GateManager.i: core/GateManager.cpp.i
.PHONY : core/GateManager.i

# target to preprocess a source file
core/GateManager.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/GateManager.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/GateManager.cpp.i
.PHONY : core/GateManager.cpp.i

core/GateManager.s: core/GateManager.cpp.s
.PHONY : core/GateManager.s

# target to generate assembly for a file
core/GateManager.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/GateManager.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/GateManager.cpp.s
.PHONY : core/GateManager.cpp.s

core/HttpClient.o: core/HttpClient.cpp.o
.PHONY : core/HttpClient.o

# target to build an object file
core/HttpClient.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/HttpClient.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/HttpClient.cpp.o
.PHONY : core/HttpClient.cpp.o

core/HttpClient.i: core/HttpClient.cpp.i
.PHONY : core/HttpClient.i

# target to preprocess a source file
core/HttpClient.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/HttpClient.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/HttpClient.cpp.i
.PHONY : core/HttpClient.cpp.i

core/HttpClient.s: core/HttpClient.cpp.s
.PHONY : core/HttpClient.s

# target to generate assembly for a file
core/HttpClient.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/HttpClient.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/HttpClient.cpp.s
.PHONY : core/HttpClient.cpp.s

core/MTHandler.o: core/MTHandler.cpp.o
.PHONY : core/MTHandler.o

# target to build an object file
core/MTHandler.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/MTHandler.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/MTHandler.cpp.o
.PHONY : core/MTHandler.cpp.o

core/MTHandler.i: core/MTHandler.cpp.i
.PHONY : core/MTHandler.i

# target to preprocess a source file
core/MTHandler.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/MTHandler.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/MTHandler.cpp.i
.PHONY : core/MTHandler.cpp.i

core/MTHandler.s: core/MTHandler.cpp.s
.PHONY : core/MTHandler.s

# target to generate assembly for a file
core/MTHandler.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/MTHandler.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/MTHandler.cpp.s
.PHONY : core/MTHandler.cpp.s

core/MessageClassifier.o: core/MessageClassifier.cpp.o
.PHONY : core/MessageClassifier.o

# target to build an object file
core/MessageClassifier.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/MessageClassifier.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/MessageClassifier.cpp.o
.PHONY : core/MessageClassifier.cpp.o

core/MessageClassifier.i: core/MessageClassifier.cpp.i
.PHONY : core/MessageClassifier.i

# target to preprocess a source file
core/MessageClassifier.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/MessageClassifier.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/MessageClassifier.cpp.i
.PHONY : core/MessageClassifier.cpp.i

core/MessageClassifier.s: core/MessageClassifier.cpp.s
.PHONY : core/MessageClassifier.s

# target to generate assembly for a file
core/MessageClassifier.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/MessageClassifier.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/MessageClassifier.cpp.s
.PHONY : core/MessageClassifier.cpp.s

core/MessagesQueue.o: core/MessagesQueue.cpp.o
.PHONY : core/MessagesQueue.o

# target to build an object file
core/MessagesQueue.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/MessagesQueue.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/MessagesQueue.cpp.o
.PHONY : core/MessagesQueue.cpp.o

core/MessagesQueue.i: core/MessagesQueue.cpp.i
.PHONY : core/MessagesQueue.i

# target to preprocess a source file
core/MessagesQueue.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/MessagesQueue.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/MessagesQueue.cpp.i
.PHONY : core/MessagesQueue.cpp.i

core/MessagesQueue.s: core/MessagesQueue.cpp.s
.PHONY : core/MessagesQueue.s

# target to generate assembly for a file
core/MessagesQueue.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/MessagesQueue.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/MessagesQueue.cpp.s
.PHONY : core/MessagesQueue.cpp.s

core/PartnerManager.o: core/PartnerManager.cpp.o
.PHONY : core/PartnerManager.o

# target to build an object file
core/PartnerManager.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/PartnerManager.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/PartnerManager.cpp.o
.PHONY : core/PartnerManager.cpp.o

core/PartnerManager.i: core/PartnerManager.cpp.i
.PHONY : core/PartnerManager.i

# target to preprocess a source file
core/PartnerManager.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/PartnerManager.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/PartnerManager.cpp.i
.PHONY : core/PartnerManager.cpp.i

core/PartnerManager.s: core/PartnerManager.cpp.s
.PHONY : core/PartnerManager.s

# target to generate assembly for a file
core/PartnerManager.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/PartnerManager.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/PartnerManager.cpp.s
.PHONY : core/PartnerManager.cpp.s

core/ReportPage.o: core/ReportPage.cpp.o
.PHONY : core/ReportPage.o

# target to build an object file
core/ReportPage.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/ReportPage.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/ReportPage.cpp.o
.PHONY : core/ReportPage.cpp.o

core/ReportPage.i: core/ReportPage.cpp.i
.PHONY : core/ReportPage.i

# target to preprocess a source file
core/ReportPage.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/ReportPage.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/ReportPage.cpp.i
.PHONY : core/ReportPage.cpp.i

core/ReportPage.s: core/ReportPage.cpp.s
.PHONY : core/ReportPage.s

# target to generate assembly for a file
core/ReportPage.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/ReportPage.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/ReportPage.cpp.s
.PHONY : core/ReportPage.cpp.s

core/RequestHandler.o: core/RequestHandler.cpp.o
.PHONY : core/RequestHandler.o

# target to build an object file
core/RequestHandler.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/RequestHandler.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/RequestHandler.cpp.o
.PHONY : core/RequestHandler.cpp.o

core/RequestHandler.i: core/RequestHandler.cpp.i
.PHONY : core/RequestHandler.i

# target to preprocess a source file
core/RequestHandler.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/RequestHandler.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/RequestHandler.cpp.i
.PHONY : core/RequestHandler.cpp.i

core/RequestHandler.s: core/RequestHandler.cpp.s
.PHONY : core/RequestHandler.s

# target to generate assembly for a file
core/RequestHandler.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/RequestHandler.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/RequestHandler.cpp.s
.PHONY : core/RequestHandler.cpp.s

core/RequestTracker.o: core/RequestTracker.cpp.o
.PHONY : core/RequestTracker.o

# target to build an object file
core/RequestTracker.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/RequestTracker.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/RequestTracker.cpp.o
.PHONY : core/RequestTracker.cpp.o

core/RequestTracker.i: core/RequestTracker.cpp.i
.PHONY : core/RequestTracker.i

# target to preprocess a source file
core/RequestTracker.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/RequestTracker.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/RequestTracker.cpp.i
.PHONY : core/RequestTracker.cpp.i

core/RequestTracker.s: core/RequestTracker.cpp.s
.PHONY : core/RequestTracker.s

# target to generate assembly for a file
core/RequestTracker.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/RequestTracker.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/RequestTracker.cpp.s
.PHONY : core/RequestTracker.cpp.s

core/Route.o: core/Route.cpp.o
.PHONY : core/Route.o

# target to build an object file
core/Route.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/Route.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/Route.cpp.o
.PHONY : core/Route.cpp.o

core/Route.i: core/Route.cpp.i
.PHONY : core/Route.i

# target to preprocess a source file
core/Route.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/Route.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/Route.cpp.i
.PHONY : core/Route.cpp.i

core/Route.s: core/Route.cpp.s
.PHONY : core/Route.s

# target to generate assembly for a file
core/Route.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/Route.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/Route.cpp.s
.PHONY : core/Route.cpp.s

core/SMPPGate.o: core/SMPPGate.cpp.o
.PHONY : core/SMPPGate.o

# target to build an object file
core/SMPPGate.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMPPGate.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMPPGate.cpp.o
.PHONY : core/SMPPGate.cpp.o

core/SMPPGate.i: core/SMPPGate.cpp.i
.PHONY : core/SMPPGate.i

# target to preprocess a source file
core/SMPPGate.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMPPGate.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMPPGate.cpp.i
.PHONY : core/SMPPGate.cpp.i

core/SMPPGate.s: core/SMPPGate.cpp.s
.PHONY : core/SMPPGate.s

# target to generate assembly for a file
core/SMPPGate.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMPPGate.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMPPGate.cpp.s
.PHONY : core/SMPPGate.cpp.s

core/SMPPGateFilterParser.o: core/SMPPGateFilterParser.cpp.o
.PHONY : core/SMPPGateFilterParser.o

# target to build an object file
core/SMPPGateFilterParser.cpp.o:
	$(MAKE) -f CMakeFiles/ghelper.dir/build.make CMakeFiles/ghelper.dir/core/SMPPGateFilterParser.cpp.o
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMPPGateFilterParser.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMPPGateFilterParser.cpp.o
.PHONY : core/SMPPGateFilterParser.cpp.o

core/SMPPGateFilterParser.i: core/SMPPGateFilterParser.cpp.i
.PHONY : core/SMPPGateFilterParser.i

# target to preprocess a source file
core/SMPPGateFilterParser.cpp.i:
	$(MAKE) -f CMakeFiles/ghelper.dir/build.make CMakeFiles/ghelper.dir/core/SMPPGateFilterParser.cpp.i
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMPPGateFilterParser.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMPPGateFilterParser.cpp.i
.PHONY : core/SMPPGateFilterParser.cpp.i

core/SMPPGateFilterParser.s: core/SMPPGateFilterParser.cpp.s
.PHONY : core/SMPPGateFilterParser.s

# target to generate assembly for a file
core/SMPPGateFilterParser.cpp.s:
	$(MAKE) -f CMakeFiles/ghelper.dir/build.make CMakeFiles/ghelper.dir/core/SMPPGateFilterParser.cpp.s
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMPPGateFilterParser.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMPPGateFilterParser.cpp.s
.PHONY : core/SMPPGateFilterParser.cpp.s

core/SMPPGateManager.o: core/SMPPGateManager.cpp.o
.PHONY : core/SMPPGateManager.o

# target to build an object file
core/SMPPGateManager.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMPPGateManager.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMPPGateManager.cpp.o
.PHONY : core/SMPPGateManager.cpp.o

core/SMPPGateManager.i: core/SMPPGateManager.cpp.i
.PHONY : core/SMPPGateManager.i

# target to preprocess a source file
core/SMPPGateManager.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMPPGateManager.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMPPGateManager.cpp.i
.PHONY : core/SMPPGateManager.cpp.i

core/SMPPGateManager.s: core/SMPPGateManager.cpp.s
.PHONY : core/SMPPGateManager.s

# target to generate assembly for a file
core/SMPPGateManager.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMPPGateManager.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMPPGateManager.cpp.s
.PHONY : core/SMPPGateManager.cpp.s

core/SMSMessage.o: core/SMSMessage.cpp.o
.PHONY : core/SMSMessage.o

# target to build an object file
core/SMSMessage.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMSMessage.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMSMessage.cpp.o
.PHONY : core/SMSMessage.cpp.o

core/SMSMessage.i: core/SMSMessage.cpp.i
.PHONY : core/SMSMessage.i

# target to preprocess a source file
core/SMSMessage.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMSMessage.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMSMessage.cpp.i
.PHONY : core/SMSMessage.cpp.i

core/SMSMessage.s: core/SMSMessage.cpp.s
.PHONY : core/SMSMessage.s

# target to generate assembly for a file
core/SMSMessage.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMSMessage.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMSMessage.cpp.s
.PHONY : core/SMSMessage.cpp.s

core/SMSRequest.o: core/SMSRequest.cpp.o
.PHONY : core/SMSRequest.o

# target to build an object file
core/SMSRequest.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMSRequest.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMSRequest.cpp.o
.PHONY : core/SMSRequest.cpp.o

core/SMSRequest.i: core/SMSRequest.cpp.i
.PHONY : core/SMSRequest.i

# target to preprocess a source file
core/SMSRequest.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMSRequest.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMSRequest.cpp.i
.PHONY : core/SMSRequest.cpp.i

core/SMSRequest.s: core/SMSRequest.cpp.s
.PHONY : core/SMSRequest.s

# target to generate assembly for a file
core/SMSRequest.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/SMSRequest.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/SMSRequest.cpp.s
.PHONY : core/SMSRequest.cpp.s

core/StatManager.o: core/StatManager.cpp.o
.PHONY : core/StatManager.o

# target to build an object file
core/StatManager.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/StatManager.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/StatManager.cpp.o
.PHONY : core/StatManager.cpp.o

core/StatManager.i: core/StatManager.cpp.i
.PHONY : core/StatManager.i

# target to preprocess a source file
core/StatManager.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/StatManager.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/StatManager.cpp.i
.PHONY : core/StatManager.cpp.i

core/StatManager.s: core/StatManager.cpp.s
.PHONY : core/StatManager.s

# target to generate assembly for a file
core/StatManager.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/StatManager.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/StatManager.cpp.s
.PHONY : core/StatManager.cpp.s

core/Tariff.o: core/Tariff.cpp.o
.PHONY : core/Tariff.o

# target to build an object file
core/Tariff.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/Tariff.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/Tariff.cpp.o
.PHONY : core/Tariff.cpp.o

core/Tariff.i: core/Tariff.cpp.i
.PHONY : core/Tariff.i

# target to preprocess a source file
core/Tariff.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/Tariff.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/Tariff.cpp.i
.PHONY : core/Tariff.cpp.i

core/Tariff.s: core/Tariff.cpp.s
.PHONY : core/Tariff.s

# target to generate assembly for a file
core/Tariff.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/core/Tariff.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/core/Tariff.cpp.s
.PHONY : core/Tariff.cpp.s

ghelper.o: ghelper.cpp.o
.PHONY : ghelper.o

# target to build an object file
ghelper.cpp.o:
	$(MAKE) -f CMakeFiles/ghelper.dir/build.make CMakeFiles/ghelper.dir/ghelper.cpp.o
.PHONY : ghelper.cpp.o

ghelper.i: ghelper.cpp.i
.PHONY : ghelper.i

# target to preprocess a source file
ghelper.cpp.i:
	$(MAKE) -f CMakeFiles/ghelper.dir/build.make CMakeFiles/ghelper.dir/ghelper.cpp.i
.PHONY : ghelper.cpp.i

ghelper.s: ghelper.cpp.s
.PHONY : ghelper.s

# target to generate assembly for a file
ghelper.cpp.s:
	$(MAKE) -f CMakeFiles/ghelper.dir/build.make CMakeFiles/ghelper.dir/ghelper.cpp.s
.PHONY : ghelper.cpp.s

smsgate.o: smsgate.cpp.o
.PHONY : smsgate.o

# target to build an object file
smsgate.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/smsgate.cpp.o
.PHONY : smsgate.cpp.o

smsgate.i: smsgate.cpp.i
.PHONY : smsgate.i

# target to preprocess a source file
smsgate.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/smsgate.cpp.i
.PHONY : smsgate.cpp.i

smsgate.s: smsgate.cpp.s
.PHONY : smsgate.s

# target to generate assembly for a file
smsgate.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/smsgate.cpp.s
.PHONY : smsgate.cpp.s

thelper.o: thelper.cpp.o
.PHONY : thelper.o

# target to build an object file
thelper.cpp.o:
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/thelper.cpp.o
.PHONY : thelper.cpp.o

thelper.i: thelper.cpp.i
.PHONY : thelper.i

# target to preprocess a source file
thelper.cpp.i:
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/thelper.cpp.i
.PHONY : thelper.cpp.i

thelper.s: thelper.cpp.s
.PHONY : thelper.s

# target to generate assembly for a file
thelper.cpp.s:
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/thelper.cpp.s
.PHONY : thelper.cpp.s

utils/PGSql.o: utils/PGSql.cpp.o
.PHONY : utils/PGSql.o

# target to build an object file
utils/PGSql.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/utils/PGSql.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/utils/PGSql.cpp.o
.PHONY : utils/PGSql.cpp.o

utils/PGSql.i: utils/PGSql.cpp.i
.PHONY : utils/PGSql.i

# target to preprocess a source file
utils/PGSql.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/utils/PGSql.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/utils/PGSql.cpp.i
.PHONY : utils/PGSql.cpp.i

utils/PGSql.s: utils/PGSql.cpp.s
.PHONY : utils/PGSql.s

# target to generate assembly for a file
utils/PGSql.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/utils/PGSql.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/utils/PGSql.cpp.s
.PHONY : utils/PGSql.cpp.s

utils/Timer.o: utils/Timer.cpp.o
.PHONY : utils/Timer.o

# target to build an object file
utils/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/utils/Timer.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/utils/Timer.cpp.o
.PHONY : utils/Timer.cpp.o

utils/Timer.i: utils/Timer.cpp.i
.PHONY : utils/Timer.i

# target to preprocess a source file
utils/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/utils/Timer.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/utils/Timer.cpp.i
.PHONY : utils/Timer.cpp.i

utils/Timer.s: utils/Timer.cpp.s
.PHONY : utils/Timer.s

# target to generate assembly for a file
utils/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/utils/Timer.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/utils/Timer.cpp.s
.PHONY : utils/Timer.cpp.s

utils/utils.o: utils/utils.cpp.o
.PHONY : utils/utils.o

# target to build an object file
utils/utils.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/utils/utils.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/utils/utils.cpp.o
.PHONY : utils/utils.cpp.o

utils/utils.i: utils/utils.cpp.i
.PHONY : utils/utils.i

# target to preprocess a source file
utils/utils.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/utils/utils.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/utils/utils.cpp.i
.PHONY : utils/utils.cpp.i

utils/utils.s: utils/utils.cpp.s
.PHONY : utils/utils.s

# target to generate assembly for a file
utils/utils.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/utils/utils.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/utils/utils.cpp.s
.PHONY : utils/utils.cpp.s

web/AdminPage.o: web/AdminPage.cpp.o
.PHONY : web/AdminPage.o

# target to build an object file
web/AdminPage.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/AdminPage.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/AdminPage.cpp.o
.PHONY : web/AdminPage.cpp.o

web/AdminPage.i: web/AdminPage.cpp.i
.PHONY : web/AdminPage.i

# target to preprocess a source file
web/AdminPage.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/AdminPage.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/AdminPage.cpp.i
.PHONY : web/AdminPage.cpp.i

web/AdminPage.s: web/AdminPage.cpp.s
.PHONY : web/AdminPage.s

# target to generate assembly for a file
web/AdminPage.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/AdminPage.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/AdminPage.cpp.s
.PHONY : web/AdminPage.cpp.s

web/CountryGatesStats.o: web/CountryGatesStats.cpp.o
.PHONY : web/CountryGatesStats.o

# target to build an object file
web/CountryGatesStats.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/CountryGatesStats.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/CountryGatesStats.cpp.o
.PHONY : web/CountryGatesStats.cpp.o

web/CountryGatesStats.i: web/CountryGatesStats.cpp.i
.PHONY : web/CountryGatesStats.i

# target to preprocess a source file
web/CountryGatesStats.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/CountryGatesStats.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/CountryGatesStats.cpp.i
.PHONY : web/CountryGatesStats.cpp.i

web/CountryGatesStats.s: web/CountryGatesStats.cpp.s
.PHONY : web/CountryGatesStats.s

# target to generate assembly for a file
web/CountryGatesStats.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/CountryGatesStats.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/CountryGatesStats.cpp.s
.PHONY : web/CountryGatesStats.cpp.s

web/LoginBlock.o: web/LoginBlock.cpp.o
.PHONY : web/LoginBlock.o

# target to build an object file
web/LoginBlock.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/LoginBlock.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/LoginBlock.cpp.o
.PHONY : web/LoginBlock.cpp.o

web/LoginBlock.i: web/LoginBlock.cpp.i
.PHONY : web/LoginBlock.i

# target to preprocess a source file
web/LoginBlock.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/LoginBlock.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/LoginBlock.cpp.i
.PHONY : web/LoginBlock.cpp.i

web/LoginBlock.s: web/LoginBlock.cpp.s
.PHONY : web/LoginBlock.s

# target to generate assembly for a file
web/LoginBlock.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/LoginBlock.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/LoginBlock.cpp.s
.PHONY : web/LoginBlock.cpp.s

web/MonitoringHandler.o: web/MonitoringHandler.cpp.o
.PHONY : web/MonitoringHandler.o

# target to build an object file
web/MonitoringHandler.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/MonitoringHandler.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/MonitoringHandler.cpp.o
.PHONY : web/MonitoringHandler.cpp.o

web/MonitoringHandler.i: web/MonitoringHandler.cpp.i
.PHONY : web/MonitoringHandler.i

# target to preprocess a source file
web/MonitoringHandler.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/MonitoringHandler.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/MonitoringHandler.cpp.i
.PHONY : web/MonitoringHandler.cpp.i

web/MonitoringHandler.s: web/MonitoringHandler.cpp.s
.PHONY : web/MonitoringHandler.s

# target to generate assembly for a file
web/MonitoringHandler.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/MonitoringHandler.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/MonitoringHandler.cpp.s
.PHONY : web/MonitoringHandler.cpp.s

web/NumberInfoPage.o: web/NumberInfoPage.cpp.o
.PHONY : web/NumberInfoPage.o

# target to build an object file
web/NumberInfoPage.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/NumberInfoPage.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/NumberInfoPage.cpp.o
.PHONY : web/NumberInfoPage.cpp.o

web/NumberInfoPage.i: web/NumberInfoPage.cpp.i
.PHONY : web/NumberInfoPage.i

# target to preprocess a source file
web/NumberInfoPage.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/NumberInfoPage.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/NumberInfoPage.cpp.i
.PHONY : web/NumberInfoPage.cpp.i

web/NumberInfoPage.s: web/NumberInfoPage.cpp.s
.PHONY : web/NumberInfoPage.s

# target to generate assembly for a file
web/NumberInfoPage.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/NumberInfoPage.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/NumberInfoPage.cpp.s
.PHONY : web/NumberInfoPage.cpp.s

web/PartnerEditor.o: web/PartnerEditor.cpp.o
.PHONY : web/PartnerEditor.o

# target to build an object file
web/PartnerEditor.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/PartnerEditor.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/PartnerEditor.cpp.o
.PHONY : web/PartnerEditor.cpp.o

web/PartnerEditor.i: web/PartnerEditor.cpp.i
.PHONY : web/PartnerEditor.i

# target to preprocess a source file
web/PartnerEditor.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/PartnerEditor.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/PartnerEditor.cpp.i
.PHONY : web/PartnerEditor.cpp.i

web/PartnerEditor.s: web/PartnerEditor.cpp.s
.PHONY : web/PartnerEditor.s

# target to generate assembly for a file
web/PartnerEditor.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/PartnerEditor.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/PartnerEditor.cpp.s
.PHONY : web/PartnerEditor.cpp.s

web/PersonalCabinet.o: web/PersonalCabinet.cpp.o
.PHONY : web/PersonalCabinet.o

# target to build an object file
web/PersonalCabinet.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/PersonalCabinet.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/PersonalCabinet.cpp.o
.PHONY : web/PersonalCabinet.cpp.o

web/PersonalCabinet.i: web/PersonalCabinet.cpp.i
.PHONY : web/PersonalCabinet.i

# target to preprocess a source file
web/PersonalCabinet.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/PersonalCabinet.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/PersonalCabinet.cpp.i
.PHONY : web/PersonalCabinet.cpp.i

web/PersonalCabinet.s: web/PersonalCabinet.cpp.s
.PHONY : web/PersonalCabinet.s

# target to generate assembly for a file
web/PersonalCabinet.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/PersonalCabinet.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/PersonalCabinet.cpp.s
.PHONY : web/PersonalCabinet.cpp.s

web/PersonalPage.o: web/PersonalPage.cpp.o
.PHONY : web/PersonalPage.o

# target to build an object file
web/PersonalPage.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/PersonalPage.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/PersonalPage.cpp.o
.PHONY : web/PersonalPage.cpp.o

web/PersonalPage.i: web/PersonalPage.cpp.i
.PHONY : web/PersonalPage.i

# target to preprocess a source file
web/PersonalPage.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/PersonalPage.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/PersonalPage.cpp.i
.PHONY : web/PersonalPage.cpp.i

web/PersonalPage.s: web/PersonalPage.cpp.s
.PHONY : web/PersonalPage.s

# target to generate assembly for a file
web/PersonalPage.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/PersonalPage.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/PersonalPage.cpp.s
.PHONY : web/PersonalPage.cpp.s

web/RoutingEditor.o: web/RoutingEditor.cpp.o
.PHONY : web/RoutingEditor.o

# target to build an object file
web/RoutingEditor.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/RoutingEditor.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/RoutingEditor.cpp.o
.PHONY : web/RoutingEditor.cpp.o

web/RoutingEditor.i: web/RoutingEditor.cpp.i
.PHONY : web/RoutingEditor.i

# target to preprocess a source file
web/RoutingEditor.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/RoutingEditor.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/RoutingEditor.cpp.i
.PHONY : web/RoutingEditor.cpp.i

web/RoutingEditor.s: web/RoutingEditor.cpp.s
.PHONY : web/RoutingEditor.s

# target to generate assembly for a file
web/RoutingEditor.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/RoutingEditor.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/RoutingEditor.cpp.s
.PHONY : web/RoutingEditor.cpp.s

web/SendMessageForm.o: web/SendMessageForm.cpp.o
.PHONY : web/SendMessageForm.o

# target to build an object file
web/SendMessageForm.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/SendMessageForm.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/SendMessageForm.cpp.o
.PHONY : web/SendMessageForm.cpp.o

web/SendMessageForm.i: web/SendMessageForm.cpp.i
.PHONY : web/SendMessageForm.i

# target to preprocess a source file
web/SendMessageForm.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/SendMessageForm.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/SendMessageForm.cpp.i
.PHONY : web/SendMessageForm.cpp.i

web/SendMessageForm.s: web/SendMessageForm.cpp.s
.PHONY : web/SendMessageForm.s

# target to generate assembly for a file
web/SendMessageForm.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/SendMessageForm.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/SendMessageForm.cpp.s
.PHONY : web/SendMessageForm.cpp.s

web/StatisticsBlock.o: web/StatisticsBlock.cpp.o
.PHONY : web/StatisticsBlock.o

# target to build an object file
web/StatisticsBlock.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/StatisticsBlock.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/StatisticsBlock.cpp.o
.PHONY : web/StatisticsBlock.cpp.o

web/StatisticsBlock.i: web/StatisticsBlock.cpp.i
.PHONY : web/StatisticsBlock.i

# target to preprocess a source file
web/StatisticsBlock.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/StatisticsBlock.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/StatisticsBlock.cpp.i
.PHONY : web/StatisticsBlock.cpp.i

web/StatisticsBlock.s: web/StatisticsBlock.cpp.s
.PHONY : web/StatisticsBlock.s

# target to generate assembly for a file
web/StatisticsBlock.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/StatisticsBlock.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/StatisticsBlock.cpp.s
.PHONY : web/StatisticsBlock.cpp.s

web/TariffEditor.o: web/TariffEditor.cpp.o
.PHONY : web/TariffEditor.o

# target to build an object file
web/TariffEditor.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/TariffEditor.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/TariffEditor.cpp.o
.PHONY : web/TariffEditor.cpp.o

web/TariffEditor.i: web/TariffEditor.cpp.i
.PHONY : web/TariffEditor.i

# target to preprocess a source file
web/TariffEditor.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/TariffEditor.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/TariffEditor.cpp.i
.PHONY : web/TariffEditor.cpp.i

web/TariffEditor.s: web/TariffEditor.cpp.s
.PHONY : web/TariffEditor.s

# target to generate assembly for a file
web/TariffEditor.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/TariffEditor.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/TariffEditor.cpp.s
.PHONY : web/TariffEditor.cpp.s

web/WScrollTable.o: web/WScrollTable.cpp.o
.PHONY : web/WScrollTable.o

# target to build an object file
web/WScrollTable.cpp.o:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/WScrollTable.cpp.o
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/WScrollTable.cpp.o
.PHONY : web/WScrollTable.cpp.o

web/WScrollTable.i: web/WScrollTable.cpp.i
.PHONY : web/WScrollTable.i

# target to preprocess a source file
web/WScrollTable.cpp.i:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/WScrollTable.cpp.i
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/WScrollTable.cpp.i
.PHONY : web/WScrollTable.cpp.i

web/WScrollTable.s: web/WScrollTable.cpp.s
.PHONY : web/WScrollTable.s

# target to generate assembly for a file
web/WScrollTable.cpp.s:
	$(MAKE) -f CMakeFiles/smsgate.dir/build.make CMakeFiles/smsgate.dir/web/WScrollTable.cpp.s
	$(MAKE) -f CMakeFiles/thelper.dir/build.make CMakeFiles/thelper.dir/web/WScrollTable.cpp.s
.PHONY : web/WScrollTable.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ghelper"
	@echo "... rebuild_cache"
	@echo "... smsgate"
	@echo "... thelper"
	@echo "... core/ConfigManager.o"
	@echo "... core/ConfigManager.i"
	@echo "... core/ConfigManager.s"
	@echo "... core/DLRHandler.o"
	@echo "... core/DLRHandler.i"
	@echo "... core/DLRHandler.s"
	@echo "... core/DeliveryHandler.o"
	@echo "... core/DeliveryHandler.i"
	@echo "... core/DeliveryHandler.s"
	@echo "... core/GateManager.o"
	@echo "... core/GateManager.i"
	@echo "... core/GateManager.s"
	@echo "... core/HttpClient.o"
	@echo "... core/HttpClient.i"
	@echo "... core/HttpClient.s"
	@echo "... core/MTHandler.o"
	@echo "... core/MTHandler.i"
	@echo "... core/MTHandler.s"
	@echo "... core/MessageClassifier.o"
	@echo "... core/MessageClassifier.i"
	@echo "... core/MessageClassifier.s"
	@echo "... core/MessagesQueue.o"
	@echo "... core/MessagesQueue.i"
	@echo "... core/MessagesQueue.s"
	@echo "... core/PartnerManager.o"
	@echo "... core/PartnerManager.i"
	@echo "... core/PartnerManager.s"
	@echo "... core/ReportPage.o"
	@echo "... core/ReportPage.i"
	@echo "... core/ReportPage.s"
	@echo "... core/RequestHandler.o"
	@echo "... core/RequestHandler.i"
	@echo "... core/RequestHandler.s"
	@echo "... core/RequestTracker.o"
	@echo "... core/RequestTracker.i"
	@echo "... core/RequestTracker.s"
	@echo "... core/Route.o"
	@echo "... core/Route.i"
	@echo "... core/Route.s"
	@echo "... core/SMPPGate.o"
	@echo "... core/SMPPGate.i"
	@echo "... core/SMPPGate.s"
	@echo "... core/SMPPGateFilterParser.o"
	@echo "... core/SMPPGateFilterParser.i"
	@echo "... core/SMPPGateFilterParser.s"
	@echo "... core/SMPPGateManager.o"
	@echo "... core/SMPPGateManager.i"
	@echo "... core/SMPPGateManager.s"
	@echo "... core/SMSMessage.o"
	@echo "... core/SMSMessage.i"
	@echo "... core/SMSMessage.s"
	@echo "... core/SMSRequest.o"
	@echo "... core/SMSRequest.i"
	@echo "... core/SMSRequest.s"
	@echo "... core/StatManager.o"
	@echo "... core/StatManager.i"
	@echo "... core/StatManager.s"
	@echo "... core/Tariff.o"
	@echo "... core/Tariff.i"
	@echo "... core/Tariff.s"
	@echo "... ghelper.o"
	@echo "... ghelper.i"
	@echo "... ghelper.s"
	@echo "... smsgate.o"
	@echo "... smsgate.i"
	@echo "... smsgate.s"
	@echo "... thelper.o"
	@echo "... thelper.i"
	@echo "... thelper.s"
	@echo "... utils/PGSql.o"
	@echo "... utils/PGSql.i"
	@echo "... utils/PGSql.s"
	@echo "... utils/Timer.o"
	@echo "... utils/Timer.i"
	@echo "... utils/Timer.s"
	@echo "... utils/utils.o"
	@echo "... utils/utils.i"
	@echo "... utils/utils.s"
	@echo "... web/AdminPage.o"
	@echo "... web/AdminPage.i"
	@echo "... web/AdminPage.s"
	@echo "... web/CountryGatesStats.o"
	@echo "... web/CountryGatesStats.i"
	@echo "... web/CountryGatesStats.s"
	@echo "... web/LoginBlock.o"
	@echo "... web/LoginBlock.i"
	@echo "... web/LoginBlock.s"
	@echo "... web/MonitoringHandler.o"
	@echo "... web/MonitoringHandler.i"
	@echo "... web/MonitoringHandler.s"
	@echo "... web/NumberInfoPage.o"
	@echo "... web/NumberInfoPage.i"
	@echo "... web/NumberInfoPage.s"
	@echo "... web/PartnerEditor.o"
	@echo "... web/PartnerEditor.i"
	@echo "... web/PartnerEditor.s"
	@echo "... web/PersonalCabinet.o"
	@echo "... web/PersonalCabinet.i"
	@echo "... web/PersonalCabinet.s"
	@echo "... web/PersonalPage.o"
	@echo "... web/PersonalPage.i"
	@echo "... web/PersonalPage.s"
	@echo "... web/RoutingEditor.o"
	@echo "... web/RoutingEditor.i"
	@echo "... web/RoutingEditor.s"
	@echo "... web/SendMessageForm.o"
	@echo "... web/SendMessageForm.i"
	@echo "... web/SendMessageForm.s"
	@echo "... web/StatisticsBlock.o"
	@echo "... web/StatisticsBlock.i"
	@echo "... web/StatisticsBlock.s"
	@echo "... web/TariffEditor.o"
	@echo "... web/TariffEditor.i"
	@echo "... web/TariffEditor.s"
	@echo "... web/WScrollTable.o"
	@echo "... web/WScrollTable.i"
	@echo "... web/WScrollTable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

