language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -y install scons
  - pushd deps/check-0.9.8
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - popd
  - scons bloomd test_libbloom_runner test_bloomd_runner
install: pip install pytest==2.3.4 --use-mirrors
script: CK_TIMEOUT_MULTIPLIER=3 ./test_libbloom_runner && ./test_bloomd_runner && py.test integ/
