//Written by: Kevin Wang
//Creates sql tables for NHTS data 
#include <iostream> 
#include <cstdlib>
#include <pqxx/pqxx>  
using namespace std; 
using namespace pqxx; 

/*Returns hardcoded strings of table creations*/
string sqlhouse();
string sqlperson();
string sqlvehicle();
string sqldaytrip();
int main(int argc, char* argv[]) {
  string user(getenv("USER"));
  try { 
    connection C("dbname=postgres user="+user); 
    if (C.is_open()) { 
      cout << "Opened database successfully: " << C.dbname() << endl; 
    } else { 
      cout << "Can't open database" << endl; 
      return 1; 
    } 
     /* Create a transactional object. */ 
    work W(C); 
     /* Execute SQL query */ 
     /*tablecreations*/
    W.exec( sqlhouse()); 
    W.exec( sqlperson());
    W.exec( sqlvehicle());
    W.exec( sqldaytrip());
    /*Commit transaction*/
    W.commit(); 
    cout << "Tables created successfully" << endl; 
    C.disconnect (); 
  } catch (const std::exception &e){ 
    cerr << e.what() << std::endl; 
    return 1; 
  } 
  return 0; 
}
/*Returns hardcoded strings of table creations*/
string sqlhouse(){
return "CREATE TABLE HOUSES("  
"HOUSEID	INTEGER PRIMARY KEY	NOT NULL,"
"VARSTRAT 	SMALLINT,"
"WTHHFIN 	REAL,"
"DRVRCNT	SMALLINT,"
"CDIVMSAR	SMALLINT,"
"CENSUS_D	SMALLINT,"
"CENSUS_R	SMALLINT,"
"HH_HISP	SMALLINT,"
"HH_RACE	SMALLINT,"
"HHFAMINC	SMALLINT,"
"HHRELATD	SMALLINT,"
"HHRESP		SMALLINT,"
"HHSIZE		SMALLINT,"
"HHSTATE	VARCHAR(2),"
"HHSTFIPS	SMALLINT,"
"HHVEHCNT	SMALLINT,"
"HOMEOWN	SMALLINT,"
"HOMETYPE	SMALLINT,"
"MSACAT		SMALLINT,"
"MSASIZE	SMALLINT,"
"NUMADLT	SMALLINT,"
"RAIL		SMALLINT,"
"RESP_CNT	SMALLINT,"
"SCRESP		SMALLINT,"
"TRAVDAY	SMALLINT,"
"URBAN		SMALLINT,"
"URBANSIZE	SMALLINT,"
"URBRUR		SMALLINT,"
"WRKCOUNT	SMALLINT,"
"TDAYDATE	INTEGER,"
"FLAG100	SMALLINT,"
"LIF_CYC	SMALLINT,"
"CNTTDHH	SMALLINT,"
"HBHUR		VARCHAR(2),"	
"HTRESDN	INTEGER,"
"HTHTNRNT	SMALLINT,"
"HTPPOPDN	INTEGER,"
"HTEEMPDN	SMALLINT,"
"HBRESDN	SMALLINT,"
"HBHTNRNT	SMALLINT,"
"HBPPOPDN	INTEGER,"
"HH_CBSA	VARCHAR(8),"
"HHC_MSA	VARCHAR(8)"
");";
}
string sqlperson(){
	return "CREATE TABLE PERSONS("
"HOUSEID	INTEGER NOT NULL,"
"PERSONID	INTEGER NOT NULL,"
"VARSTRAT	SMALLINT,"
"WTPERFIN	INTEGER,"
"SFWGT		INTEGER,"
"CNTTDTR	SMALLINT,"
"BORNINUS	SMALLINT,"
"CARRODE	SMALLINT,"
"CONDNIGH	SMALLINT,"
"CONDPUB	SMALLINT,"
"CONDRIDE 	SMALLINT,"
"CONDRIVE	SMALLINT,"
"CONDSPEC	SMALLINT,"
"CONDTAX	SMALLINT,"
"CONDTRAV	SMALLINT,"
"DELIVER	SMALLINT,"
"DIARY		SMALLINT,"
"DISTTOSC	SMALLINT,"
"DTACDT		SMALLINT,"
"DTCONJ		SMALLINT,"
"DTCOST		SMALLINT,"
"DTRAGE		SMALLINT,"
"DTRAN		SMALLINT,"
"DTWALK		SMALLINT,"
"EVERDROV	SMALLINT,"
"FLEXTIME	SMALLINT,"
"FMSCSIZE	SMALLINT,"
"FRSTHM 	SMALLINT,"
"FXDWKPL 	SMALLINT,"
"GCDWORK	SMALLINT,"
"GRADE 		SMALLINT,"
"GT1JBLWK 	SMALLINT,"
"ISSUE 		SMALLINT,"
"OCCAT	 	SMALLINT,"
"LSTTRDAY	SMALLINT,"
"MCUSED		SMALLINT,"
"MEDCOND 	SMALLINT,"
"MEDCOND6 	SMALLINT,"
"MOROFTEN 	SMALLINT,"
"NBIKETRP	SMALLINT,"
"NWALKTRP	SMALLINT,"
"OUTCNTRY 	SMALLINT,"
"PAYPROF 	SMALLINT,"
"PTUSED		SMALLINT,"
"PURCHASE	SMALLINT,"
"R_RELAT 	SMALLINT,"
"SAMEPLC 	SMALLINT,"
"SCHCARE 	SMALLINT,"
"SCHCRIM 	SMALLINT,"
"SCHDIST 	SMALLINT,"
"SCHSPD 	SMALLINT,"
"SCHTRAF 	SMALLINT,"
"SCHTRN1 	SMALLINT,"
"SCHTRN2 	SMALLINT,"
"SCHTYP 	SMALLINT,"
"SCHWTHR 	SMALLINT,"
"SELF_EMP 	SMALLINT,"
"TIMETOSC	SMALLINT,"
"TIMETOWK	SMALLINT,"
"TOSCSIZE	SMALLINT,"
"WEBUSE 	SMALLINT,"
"WKFMHMXX	SMALLINT,"
"WKFTPT 	SMALLINT,"
"WKRMHM 	SMALLINT,"
"WKSTFIPS 	SMALLINT,"
"WRKTIME	VARCHAR(8),"
"WRKTRANS 	SMALLINT,"
"YEARMILE	INTEGER,"
"YRMLCAP 	SMALLINT,"
"YRTOUS		SMALLINT,"
"DISTTOWK	SMALLINT,"
"PRIMARY KEY(HOUSEID, PERSONID)"
");";
}

string sqlvehicle(){
	return "CREATE TABLE VEHICLES("
"HOUSEID	INTEGER NOT NULL,"
"VEHID		INTEGER NOT NULL,"
"HYBRID		SMALLINT,"
"MAKECODE	VARCHAR(2),"//if = "XX", then is NULL
"MODLCODE	VARCHAR(3),"
"OD_READ	INTEGER,"
"VEHCOMM	SMALLINT,"
"VEHOWNMO	SMALLINT,"
"VEHYEAR	SMALLINT,"
"WHOMAIN	SMALLINT,"
"VEHAGE		SMALLINT,"
"PERSONID	INTEGER NOT NULL,"
"ANNMILES	INTEGER,"
"BEST_FLG	SMALLINT,"
"BESTMILE	INTEGER,"
"BEST_EDT	SMALLINT,"
"BEST_OUT	SMALLINT,"
"FUELTYPE	SMALLINT,"
"GSYRGAL	INTEGER,"
"GSCOST		REAL,"
"GSTOTCST	INTEGER,"
"EPATMPG	REAL,"
"EPATMPGF	SMALLINT,"
"EIADMPG	REAL,"
"VEHTYPE	SMALLINT,"
"PRIMARY KEY(HOUSEID, VEHID, PERSONID)"
");";
}

string sqldaytrip(){
	return "CREATE TABLE DAYTRIP("
"HOUSEID	INTEGER NOT NULL,"
"PERSONID	INTEGER NOT NULL,"
"ONTD_P1	SMALLINT,"
"ONTD_P2	SMALLINT,"
"ONTD_P3	SMALLINT,"
"ONTD_P4	SMALLINT,"
"ONTD_P5	SMALLINT,"
"ONTD_P6	SMALLINT,"
"ONTD_P7	SMALLINT,"
"ONTD_P8	SMALLINT,"
"ONTD_P9	SMALLINT,"
"ONTD_P10	SMALLINT,"
"ONTD_P11	SMALLINT,"
"ONTD_P12	SMALLINT,"
"ONTD_P13	SMALLINT,"
"ONTD_P14	SMALLINT,"
"ONTD_P15	SMALLINT,"
"TDCASEID	BIGINT,"
"TRIPPURP	VARCHAR(8),"//NOTINT
"AWAYHOME	SMALLINT,"
"DROP_PRK	SMALLINT,"
"DRVR_FLG	SMALLINT,"
"ENDTIME	SMALLINT,"
"HH_ONTD	SMALLINT,"
"HHMEMDRV	SMALLINT,"
"INTSTATE	SMALLINT,"
"NONHHCNT	SMALLINT,"
"NUMONTRP	SMALLINT,"
"PAYTOLL	SMALLINT,"
"PSGR_FLG	SMALLINT,"
"STRTTIME	INTEGER,"
"TRACC1		SMALLINT,"
"TRACC2		SMALLINT,"
"TRACC3		SMALLINT,"
"TRACC4		SMALLINT,"
"TRACC5		SMALLINT,"
"TRACCTM	SMALLINT,"
"TREGR1		SMALLINT,"
"TREGR2		SMALLINT,"
"TREGR3		SMALLINT,"
"TREGR4		SMALLINT,"
"TREGR5		SMALLINT,"
"TREGRTM	SMALLINT,"
"TRPACCMP	SMALLINT,"
"TRPHHACC	SMALLINT,"
"TRPHHVEH	SMALLINT,"
"TRPTRANS	SMALLINT,"
"TRVL_MIN	SMALLINT,"
"TRVLCMIN	SMALLINT,"
"TRWAITTM	SMALLINT,"
"VEHID		INTEGER NOT NULL,"
"WHODROVE	SMALLINT,"
"WHYFROM	SMALLINT,"
"WHYTO		SMALLINT,"
"WHYTRP1S	SMALLINT,"
"DWELTIME	SMALLINT,"
"WHYTRP90	SMALLINT,"
"TDTRPNUM	SMALLINT,"
"TDWKND		INTEGER,"
"TDAYDATE	INTEGER,"
"TRPMILES	SMALLINT,"
"WTTRDFIN	INTEGER,"
"VMT_MILE	SMALLINT,"
"PUBTRANS	SMALLINT,"
"GASPRICE	REAL,"
"PRIMARY KEY(HOUSEID, PERSONID, VEHID, TDTRPNUM)"
");";
}
