language: erlang

env:
  - LUA="luajit" LUA_PATH="lib/?.lua;;"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script: "busted spec"
